apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: gateway-integrate-dc
  name: gateway-integrate-dc
  namespace: aiot-dc
spec:
  replicas: 2
  selector:
    matchLabels:
      io.kompose.service: gateway-integrate-dc
  template:
    metadata:
      labels:
        io.kompose.service: gateway-integrate-dc
    spec:
      containers:
        - image: aiot/gateway-integrate:latest
          name: gateway-integrate
          ports:
            - containerPort: 8006
          env:
            - name: INFLUX_ADDR
              value: http://10.38.170.215:8086
            - name: INFLUX_USERNAME
              value: mainflux
            - name: INFLUX_PASSWORD
              value: mainflux
            - name: INFLUX_DB
              value: mainflux
            - name: MQTT_BROKER
              value: 10.38.170.215:1883
            - name: VERNEMQ_ADDR
              value: 10.38.170.215
            - name: VERNEMQ_PORT
              value: 8888
            - name: VERNEMQ_API_KEY
              value: oSEWJLIeUVSCWuPGoKgvSxew7Eco935m
            - name: AUTH_REDIS_ADDR
              value: auth-redis:6379
            - name: AUTH_REDIS_PASSWORD
              value:
            - name: AUTH_REDIS_DB
              value: "0"
            - name: HTTP_SERVER_PORT
              value: "8006"
            - name: GIN_MODE
              value: release
          imagePullPolicy: IfNotPresent
      restartPolicy: Always
      nodeSelector: node-restriction.kubernetes.io/nodelocation=aiotdc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: gateway-integrate-dc
  name: gateway-integrate-dc
  namespace: aiot-dc
spec:
  type: NodePort
  ports:
    - name: "38006"
      port: 8006
      targetPort: 8006
      nodePort: 38006
  selector:
    io.kompose.service: gateway-integrate-dc
